<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['resource_report_app_description'] = 'Отчет о ресурсах включает в себя информацию о загрузке, использовании памяти и рабочих процессах.';
$lang['resource_report_app_name'] = 'Отчет о ресурсах';
$lang['resource_report_load_average'] = 'Load Average';
$lang['resource_report_number_of_processes'] = 'Number of Processes';
