<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['resource_report_app_description'] = 'The Resource Report includes information on load, memory usage and running processes.';
$lang['resource_report_app_name'] = 'Resource Report';
$lang['resource_report_load_average'] = 'Load Average';
$lang['resource_report_number_of_processes'] = 'Number of Processes';
