<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['resource_report_app_description'] = 'Raport zasobów zawiera informacje nt. aktualnego obciążenia, użycia pamięci oraz działających procesów. ';
$lang['resource_report_app_name'] = 'Raport zasobów';
$lang['resource_report_load_average'] = 'Średnie obciążenie';
$lang['resource_report_number_of_processes'] = 'Liczba procesów';
